// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoFcaoh4OwVMvSe5u6rPpSeEJ0Zbl_4Ds',
    appId: '1:73720588788:web:154425f469b988725c31a1',
    messagingSenderId: '73720588788',
    projectId: 'chat-app-4784f',
    authDomain: 'chat-app-4784f.firebaseapp.com',
    storageBucket: 'chat-app-4784f.appspot.com',
    measurementId: 'G-D5J21022BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKKPqatvTI-M1eJ-By_bkjGv0uboLkd0',
    appId: '1:73720588788:android:45df8b1bfc1962db5c31a1',
    messagingSenderId: '73720588788',
    projectId: 'chat-app-4784f',
    storageBucket: 'chat-app-4784f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhEQm16Tm-mhbJjK1jczEQTWdU9hOt5M',
    appId: '1:73720588788:ios:8e0389c6729dc2685c31a1',
    messagingSenderId: '73720588788',
    projectId: 'chat-app-4784f',
    storageBucket: 'chat-app-4784f.appspot.com',
    iosClientId: '73720588788-82rs6s3jnellb47p8n1gatt0elen8muc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKhEQm16Tm-mhbJjK1jczEQTWdU9hOt5M',
    appId: '1:73720588788:ios:031ed1844d9cf83c5c31a1',
    messagingSenderId: '73720588788',
    projectId: 'chat-app-4784f',
    storageBucket: 'chat-app-4784f.appspot.com',
    iosClientId: '73720588788-jc7hvadpn3kc7doar8s9dqn77528dpdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
